name: twitterGPT

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.10.6"

      - name: Get Dependencies
        run: flutter pub get

      - name: Create .env file
        run: |
          echo '${{ secrets.ENV_FILE_CONTENT }}' > .env

      - name: Run Analyzer
        run: flutter analyze

      - name: Build APK
        run: flutter build apk

      # - name: Build iOS
      #   run: flutter build ios --no-codesign

      - name: Archive APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # - name: Archive iOS build
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: Runner.app
      #     path: build/ios/iphoneos/Runner.app

    # - name: Deploy to Server
    #   run: |
    #     Your deployment commands here
    #   env:
    #     DEPLOYMENT_SERVER: ${{ secrets.DEPLOYMENT_SERVER }}
    #     DEPLOYMENT_USER: ${{ secrets.DEPLOYMENT_USER }}
    #     DEPLOYMENT_PASSWORD: ${{ secrets.DEPLOYMENT_PASSWORD }}
